version: 2.1
jobs:
  kics:
    docker:
      - image: cosmicgirl/kics
    steps:
      - checkout
      - run:
          name: Run KICS
          command: |
            /app/bin/kics scan -p ${PWD} -o results -v --report-formats json,junit
      - store_artifacts:
          path: results

workflows:
  version: 2
  build:
    jobs:
      # etc...
      - kics
